# set module settings
# vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
/control/alias nperiods 39
/control/alias nlayers 13
/control/alias nmods 5
# ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/custom/NPeriods {nperiods}
/custom/NLayers {nlayers}
/custom/NStackedMods {nmods}

# set output file path
# vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
/custom/OutFilePath /eos/experiment/newtile/simulations/proto_studies/26_08_full_mod_stack
# ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

/control/execute 2608test__scan_settings.mac {nmods} {nlayers} {nperiods}

/run/initialize

################
# SCAN 0 - pi+ #
################
/control/alias particle pi+
/control/execute 2608test__scan_energy_divergence.mac {file_prefix} {nevs} {particle} {pos_sigma}

###############
# SCAN 1 - e+ #
###############
/control/alias particle e+
/control/execute 2608test__scan_energy_divergence.mac {file_prefix} {nevs} {particle} {pos_sigma}
