# Required aliases:
# {file_prefix}
# {nevs}
# {particle}
# {energy}
# {ang_sigma_x}
# {ang_sigma_y}
# {pos_sigma_x}
# {pos_sigma_y}

/custom/OutFileName {file_prefix}__{particle}_{energy}GeV_{nevs}evs
/custom/OutTreeTitle output data, {energy}-GeV {particle} on {file_prefix}

/gps/particle {particle}

/gps/ene/type Mono
/gps/energy {energy} GeV

/gps/ang/type beam2d
/gps/ang/rot1 1 0 0
/gps/ang/rot2 0 -1 0
/gps/ang/sigma_x {ang_sigma_x} mrad
/gps/ang/sigma_y {ang_sigma_y} mrad

/gps/pos/type Beam
/gps/pos/centre 0 0 0 m
/gps/pos/sigma_x {pos_sigma_x} cm
/gps/pos/sigma_y {pos_sigma_y} cm

/run/beamOn {nevs}
