# set module settings
# vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
/control/alias nperiods 39
/control/alias nlayers 13
/control/alias nmods 1
/control/alias coarsero 2
/control/alias bsupport true
# ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/custom/NPeriods {nperiods}
/custom/NLayers {nlayers}
/custom/NStackedMods {nmods}
/custom/CoarseRO {coarsero}
/custom/BPlaceSupport {bsupport}

# set event nr per run here
# vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
/control/alias nevs 100000
# ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

# set beam positional half-size
# vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
/control/alias pos_sigma 1
# ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

# set output file path and name prefix
# vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
/custom/OutFilePath /eos/experiment/newtile/simulations/proto_studies/26_08_full_mod_stack
/control/alias file_prefix m{nmods}_l{nlayers}_p{nperiods}_c{coarsero}_s{bsupport}
# ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

/run/initialize

################
# SCAN 0 - pi+ #
################
/control/alias particle pi+
/control/execute macros/26_08_scan_block_energy_divergence.mac

###############
# SCAN 1 - e+ #
###############
/control/alias particle e+
/control/execute macros/26_08_scan_block_energy_divergence.mac
