# Required aliases:
# {file_prefix}
# {nevs}
# {particle}
# {pos_sigma}

# --> 0.0 - 2 GeV
# set beam params here
# vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
/control/alias energy 2
/control/alias ang_sigma 3
# ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/control/alias ang_sigma_x {ang_sigma}
/control/alias ang_sigma_y {ang_sigma}
/control/alias pos_sigma_x {pos_sigma}
/control/alias pos_sigma_y {pos_sigma}
/control/execute macros/26_08_scan_point.mac

# --> 0.1 - 5 GeV
# set beam params here
# vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
/control/alias energy 5
/control/alias ang_sigma 2.5
# ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/control/alias ang_sigma_x {ang_sigma}
/control/alias ang_sigma_y {ang_sigma}
/control/alias pos_sigma_x {pos_sigma}
/control/alias pos_sigma_y {pos_sigma}
/control/execute macros/26_08_scan_point.mac

# --> 0.2 - 10 GeV
# set beam params here
# vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
/control/alias energy 10
/control/alias ang_sigma 2
# ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/control/alias ang_sigma_x {ang_sigma}
/control/alias ang_sigma_y {ang_sigma}
/control/alias pos_sigma_x {pos_sigma}
/control/alias pos_sigma_y {pos_sigma}
/control/execute macros/26_08_scan_point.mac

# --> 0.3 - 20 GeV
# set beam params here
# vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
/control/alias energy 20
/control/alias ang_sigma 1.5
# ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/control/alias ang_sigma_x {ang_sigma}
/control/alias ang_sigma_y {ang_sigma}
/control/alias pos_sigma_x {pos_sigma}
/control/alias pos_sigma_y {pos_sigma}
/control/execute macros/26_08_scan_point.mac

# --> 0.4 - 50 GeV
# set beam params here
# vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
/control/alias energy 50
/control/alias ang_sigma 1
# ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/control/alias ang_sigma_x {ang_sigma}
/control/alias ang_sigma_y {ang_sigma}
/control/alias pos_sigma_x {pos_sigma}
/control/alias pos_sigma_y {pos_sigma}
/control/execute macros/26_08_scan_point.mac

# --> 0.5 - 100 GeV
# set beam params here
# vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
/control/alias energy 100
/control/alias ang_sigma 0.5
# ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/control/alias ang_sigma_x {ang_sigma}
/control/alias ang_sigma_y {ang_sigma}
/control/alias pos_sigma_x {pos_sigma}
/control/alias pos_sigma_y {pos_sigma}
/control/execute macros/26_08_scan_point.mac

# --> 0.6 - 200 GeV
# set beam params here
# vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
/control/alias energy 200
/control/alias ang_sigma 0.1
# ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/control/alias ang_sigma_x {ang_sigma}
/control/alias ang_sigma_y {ang_sigma}
/control/alias pos_sigma_x {pos_sigma}
/control/alias pos_sigma_y {pos_sigma}
/control/execute macros/26_08_scan_point.mac

# --> 0.7 - 300 GeV
# set beam params here
# vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
/control/alias energy 300
/control/alias ang_sigma 0.05
# ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/control/alias ang_sigma_x {ang_sigma}
/control/alias ang_sigma_y {ang_sigma}
/control/alias pos_sigma_x {pos_sigma}
/control/alias pos_sigma_y {pos_sigma}
/control/execute macros/26_08_scan_point.mac

# --> 0.8 - 500 GeV
# set beam params here
# vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
/control/alias energy 500
/control/alias ang_sigma 0.02
# ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/control/alias ang_sigma_x {ang_sigma}
/control/alias ang_sigma_y {ang_sigma}
/control/alias pos_sigma_x {pos_sigma}
/control/alias pos_sigma_y {pos_sigma}
/control/execute macros/26_08_scan_point.mac
