# SET - issue custom commands here
# vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

# ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

# initialise the simulation
/run/initialize

# basic graphical settings
/vis/open OGLSQt
/vis/drawVolume
/vis/scene/add/trajectories smooth
/vis/scene/endOfEventAction accumulate

# SET - optional graphical commands (can be commented)
# --> cartesian reference (at the centre of the world)
/vis/scene/add/axes 0 0 0

# don't shoot anything --> waiting for manual input from the GUI
